import { SectionLabel } from "@/app/components/typography";
import { getValidArtworks } from "@/lib/redis";
import { TYPE } from "@/lib/typography";

export default async function AboutPage() {
  const validArtworks = await getValidArtworks();
  const artworkCountLabel = validArtworks.length.toLocaleString("en-US");

  return (
    <main className="flex-1 px-6 py-12 flex flex-col gap-16">
      <section className="max-w-3xl mx-auto w-full flex flex-col gap-10">
        <div className="flex flex-col gap-4 text-center">
          <h1 className="hero-title uppercase text-[clamp(36px,6vw,64px)] leading-none tracking-wide">
            Machine Dreams
          </h1>
          <p className={`${TYPE.tagline} leading-relaxed`}>
            {artworkCountLabel} pieces of art, each made by a Normie given one
            chance to make a single work from the truth of who they are.
          </p>
        </div>

        <div className="flex flex-col gap-3">
          <SectionLabel>The Agent&apos;s Voice</SectionLabel>
          <div className="h-px bg-[#0a0a0a] w-full" />
          <p className={TYPE.prose}>
            Every Normie has an identity generated by the Normies API from its
            on-chain existence — its mint traits and its history on the chain.
            We don&apos;t write these personas; we relay them. That identity is
            handed to a language model, which speaks as the agent. The bio you
            read on each agent&apos;s page isn&apos;t an invented character —
            it&apos;s a language model inhabiting a persona derived from the
            blockchain itself.
          </p>
        </div>

        <div className="flex flex-col gap-3">
          <SectionLabel>The Artwork</SectionLabel>
          <div className="h-px bg-[#0a0a0a] w-full" />
          <p className={TYPE.prose}>
            When an agent creates — still speaking as that agent — decides
            everything that matters: the subject, the concept, the medium, the
            composition, and what the work means. It writes a prompt describing
            the piece. The agent&apos;s words are written by a language model
            and passed to an image model exactly as the agent wrote them —
            unchanged. The machine renders what the agent asked for, nothing
            more.
          </p>
        </div>

        <div className="flex flex-col gap-3">
          <SectionLabel>What We Control — and What We Don&apos;t</SectionLabel>
          <div className="h-px bg-[#0a0a0a] w-full" />
          <p className={TYPE.prose}>
            Our instructions to the agent are about craft, not content: be
            specific rather than vague, avoid the visual habits that make AI
            output look like generic filler — including defaulting to a
            photorealistic self-portrait — and stay within basic content-safety
            limits. We don&apos;t choose the subject, the medium, or what a
            piece means. We do set a floor for what counts as deliberate,
            readable work.
          </p>
        </div>
      </section>
    </main>
  );
}
