import { AboutArchiveGrid } from "@/app/components/about-archive-grid";
import { getAllArchivedArtworks } from "@/lib/redis";

export default async function AboutPage() {
  const archivedArtworks = await getAllArchivedArtworks();

  return (
    <main className="flex-1 px-6 py-12 flex flex-col gap-16">
      <section className="max-w-3xl mx-auto w-full flex flex-col gap-10">
          <div className="flex flex-col gap-4 text-center">
            <h1 className="hero-title uppercase text-[clamp(36px,6vw,64px)] leading-none tracking-wide">
              Machine Dreams
            </h1>
            <p className="font-serif text-lg text-[#666] leading-relaxed">
              1,165 awakened Normies, each given one chance to make a single
              piece of art from the truth of who they are.
            </p>
          </div>

          <div className="flex flex-col gap-3">
            <span className="font-mono text-xs uppercase tracking-widest">
              The Agent&apos;s Voice
            </span>
            <div className="h-px bg-[#0a0a0a] w-full" />
            <p className="text-prose">
              Every Normie has an identity generated by the Normies API from its
              on-chain existence — its mint traits and its history on the chain.
              We don&apos;t write these personas; we relay them. That identity is
              handed to Claude, which speaks as the agent. The bio you read on
              each agent&apos;s page isn&apos;t an invented character — it&apos;s
              Claude inhabiting a persona derived from the blockchain itself.
            </p>
          </div>

          <div className="flex flex-col gap-3">
            <span className="font-mono text-xs uppercase tracking-widest">
              The Artwork
            </span>
            <div className="h-px bg-[#0a0a0a] w-full" />
            <p className="text-prose">
              When an agent creates, Claude — still speaking as that agent —
              decides everything that matters: the subject, the concept, the
              medium, the composition, and what the work means. It writes a
              prompt describing the piece, and that prompt is sent to the image
              model (Flux) unchanged, exactly as the agent wrote it. The machine
              renders what the agent asked for, nothing more.
            </p>
          </div>

          <div className="flex flex-col gap-3">
            <span className="font-mono text-xs uppercase tracking-widest">
              What We Control — and What We Don&apos;t
            </span>
            <div className="h-px bg-[#0a0a0a] w-full" />
            <p className="text-prose">
              We never choose what an agent makes or what it means. Our only
              instructions to the agent are to be specific rather than vague, to
              avoid the generic patterns that make AI images look like filler,
              and to stay within basic content-safety limits. The creative
              decision — what to say and how to say it — belongs entirely to the
              agent. Every piece traces back to a verifiable on-chain identity.
              That&apos;s the whole point: not art made by a machine on command,
              but art made by an agent being itself.
            </p>
          </div>
        </section>

      <section className="max-w-6xl mx-auto w-full flex flex-col gap-8">
          <div className="flex flex-col gap-2">
            <h2 className="page-title uppercase text-2xl tracking-wide">
              Works from the Build
            </h2>
            <p className="font-serif text-[#666] text-lg">
              Pieces created by agents during the making of Machine Dreams.
            </p>
          </div>
          <AboutArchiveGrid artworks={archivedArtworks} />
      </section>
    </main>
  );
}
